### ISSUE TITLE
Number pad enter key

### ISSUE THREAD

**Issue by bmauger** [tobius/laptop#1]
It would be great if Laptop supported use of the number pad enter key on full size keyboards!

**Comment by tobius** [comment]
Are you using Yosemite? If so there is a Terminal setting that controls this, here's a link discussing it: http://apple.stackexchange.com/questions/151873/yosemite-upgrade-changed-numeric-keypad-enter-key-to-issue-33om

**Comment by bmauger** [comment]
Nice! Thanks!!




Bryan Mauger

Developer

______



Resource/Ammirati

o. 614 621 2888

d. 614 947 3221

reel<https://youtu.be/uNJrC1pYVnM>. blog<http://www.resource.com/wethink-blog/>. twitter<https://twitter.com/resource>. instagram<http://www.instagram.com/ResourceAmmirati>.


resourceammirati.com<http://www.resourceammirati.com/>
